# Generated by Django 3.2 on 2023-01-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added',
            new_name='date_added',
        ),
    ]
