# Generated by Django 3.2 on 2022-11-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221120_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='format: reqd, max_length=2500', max_length=2500, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(help_text='format: reqd, max_length=2500', max_length=2500, verbose_name='How to use'),
        ),
    ]
