# Generated by Django 3.2 on 2022-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
