# Generated by Django 3.2 on 2022-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
