# Generated by Django 3.2 on 2022-12-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_Category',
            new_name='MainCategory',
        ),
    ]
