# Generated by Django 3.2 on 2022-12-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_main_category_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
