# Generated by Django 3.2 on 2022-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
