# Generated by Django 3.2 on 2022-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='format: required, max_length=200', max_length=200, verbose_name='Product name'),
        ),
    ]
