# Generated by Django 3.2 on 2023-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_wishlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
